---
files: ^(.*\.(py|json|md|sh|yaml|cfg|txt))$
exclude: ^(\.[^/]*cache/.*|.*/_user.py|LICENSE.md)$
repos:
  - repo: https://github.com/verhovsky/pyupgrade-docs
    rev: v0.3.0
    hooks:
      - id: pyupgrade-docs
  - repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat  # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, '75', --number]
        additional_dependencies:
          - mdformat-toc
          - mdformat-beautysh
          # -mdformat-shfmt
          # -mdformat-tables
          - mdformat-config
          - mdformat-black
          - mdformat-web
          - mdformat-gfm
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.6.0]
        stages: [manual]   # Manual because already done by mdformat-black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: check-case-conflict
      # - id: check-toml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args:
          - --no-warnings
          - -d
          - '{extends: relaxed, rules: {line-length: {max: 90}}}'
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: v6.2.1
    hooks:
      - id: beautysh
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.3
    hooks:
      - id: pyupgrade
        args:
          - --py39-plus
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
          - -l 79
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--skip, 'B101,B105,B311', --recursive, .]

  - repo: https://github.com/fsouza/autoflake8
    rev: v0.4.0
    hooks:
      - id: autoflake8
        args:
          - -i
          - -r
          - --expand-star-imports
          - custom_components
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          # - pyproject-flake8>=0.0.1a5
          - flake8-bugbear>=22.7.1
          - flake8-comprehensions>=3.10.1
          - flake8-2020>=1.7.0
          - mccabe>=0.7.0
          - pycodestyle>=2.9.1
          - pyflakes>=2.5.0
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        exclude: ^(.*/translations/.*)$
        args:
          # - --builtin=clear,rare,informal,usage,code,names,en-GB_to_en-US
          - --builtin=clear,rare,informal,usage,code,names
          - --ignore-words-list=hass,master
          - --skip="./.*"
          - --quiet-level=2
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args:
          - --reports=no
          - --py-version=3.9
        # exclude: ^$
        additional_dependencies:
          - homeassistant-stubs==2022.12.9
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --check-untyped-defs
          - --show-error-codes
          - --show-error-context
          - --explicit-package-bases
        additional_dependencies:
          - homeassistant-stubs==2022.12.9
